# Usar uma versão mais recente do Nginx base se possível
FROM nginx:1.23.3-alpine

# Remover configuração padrão
RUN rm /etc/nginx/conf.d/default.conf

# Copiar sua configuração personalizada
COPY default.conf /etc/nginx/conf.d/

# Expõe a porta 8080 para o contêiner
EXPOSE 8080